import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x070b0a);scene.fog=new THREE.FogExp2(0x08100d,.018);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,500);camera.position.set(0,1.7,8);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0x8ea68d,0x15120f,1.3));const moon=new THREE.DirectionalLight(0xc4d2bf,2);moon.position.set(-20,30,10);moon.castShadow=true;moon.shadow.mapSize.set(1024,1024);scene.add(moon);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0x18201b,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const grid=new THREE.GridHelper(180,60,0x344038,0x1d2821);grid.position.y=.012;grid.material.transparent=true;grid.material.opacity=.23;scene.add(grid);
for(let i=0;i<50;i++){const h=THREE.MathUtils.randFloat(1,5),m=new THREE.Mesh(new THREE.BoxGeometry(THREE.MathUtils.randFloat(.4,1.6),h,THREE.MathUtils.randFloat(.4,1.6)),new THREE.MeshStandardMaterial({color:0x202923,roughness:1}));m.position.set(THREE.MathUtils.randFloatSpread(90),h/2,THREE.MathUtils.randFloatSpread(90));m.castShadow=m.receiveShadow=true;scene.add(m)}

const gun=new THREE.Group();const gunMat=new THREE.MeshStandardMaterial({color:0x151817,metalness:.7,roughness:.3});const wood=new THREE.MeshStandardMaterial({color:0x553c25,roughness:.8});
const body=new THREE.Mesh(new THREE.BoxGeometry(.18,.22,.7),gunMat);body.position.set(.02,-.02,-.3);gun.add(body);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.045,.055,.65,10),gunMat);barrel.rotation.x=Math.PI/2;barrel.position.set(.02,.01,-.88);gun.add(barrel);const grip=new THREE.Mesh(new THREE.BoxGeometry(.13,.32,.15),wood);grip.position.set(.02,-.25,-.08);grip.rotation.x=-.15;gun.add(grip);const sight=new THREE.Mesh(new THREE.BoxGeometry(.035,.05,.14),gunMat);sight.position.set(.02,.14,-.55);gun.add(sight);gun.position.set(.42,-.32,-.72);camera.add(gun);scene.add(camera);

const keys={};let locked=false,running=false,score=0,wave=1,hp=100,ammo=12,reloading=false,gameStarted=false,gameOver=false;const zombies=[],bullets=[];const clock=new THREE.Clock();const raycaster=new THREE.Raycaster();const center=new THREE.Vector2(0,0);
const scoreEl=document.querySelector('#score'),waveEl=document.querySelector('#wave'),ammoEl=document.querySelector('#ammo'),healthBar=document.querySelector('#healthBar'),healthText=document.querySelector('#healthText'),message=document.querySelector('#message');
function zombie(){const g=new THREE.Group();const skin=new THREE.MeshStandardMaterial({color:0x4d674f,roughness:.95});const dark=new THREE.MeshStandardMaterial({color:0x151b17});const head=new THREE.Mesh(new THREE.SphereGeometry(.32,10,8),skin);head.position.y=1.65;const torso=new THREE.Mesh(new THREE.BoxGeometry(.55,.75,.34),skin);torso.position.y=1.02;const arm=new THREE.BoxGeometry(.14,.65,.14),leg=new THREE.BoxGeometry(.16,.65,.16);for(const x of [-.38,.38]){const a=new THREE.Mesh(arm,skin);a.position.set(x,1.02,0);a.rotation.z=x>0?-.25:.25;g.add(a);const l=new THREE.Mesh(leg,dark);l.position.set(x*.55,.45,0);g.add(l)}const eyeGeo=new THREE.SphereGeometry(.045,6,6);const eyeMat=new THREE.MeshBasicMaterial({color:0xff5544});for(const x of [-.11,.11]){const e=new THREE.Mesh(eyeGeo,eyeMat);e.position.set(x,1.7,-.29);g.add(e)}g.add(head,torso);g.userData={hp:2,speed:THREE.MathUtils.randFloat(.75,1.25)+wave*.055,attack:0,parts:[head,torso]};const a=Math.random()*Math.PI*2,r=THREE.MathUtils.randFloat(24,42);g.position.set(Math.cos(a)*r,0,Math.sin(a)*r);scene.add(g);zombies.push(g)}
function spawnWave(){for(let i=0;i<4+wave*2;i++)zombie();showMessage(`WAVE ${wave}`,1200);waveEl.textContent=wave}
function showMessage(t,ms=900){message.textContent=t;message.classList.remove('hidden');setTimeout(()=>message.classList.add('hidden'),ms)}
function updateHUD(){scoreEl.textContent=score;ammoEl.textContent=`${ammo} / ∞`;healthText.textContent=Math.ceil(hp);healthBar.style.width=`${Math.max(0,hp)}%`}
function shoot(){if(!locked||reloading||gameOver||ammo<=0)return;if(ammo===0)return;ammo--;updateHUD();gun.position.z=-.64;setTimeout(()=>gun.position.z=-.72,55);raycaster.setFromCamera(center,camera);const hits=raycaster.intersectObjects(scene.children,true);for(const h of hits){let o=h.object;while(o.parent&&!o.userData.hp)o=o.parent;if(o.userData.hp){o.userData.hp--;o.scale.multiplyScalar(.96);score+=o.userData.hp===0?100:20;if(o.userData.hp===0){scene.remove(o);zombies.splice(zombies.indexOf(o),1);if(zombies.length===0&&gameStarted){wave++;setTimeout(spawnWave,1200)}}updateHUD();break}}}
function reload(){if(reloading||ammo===12||gameOver)return;reloading=true;showMessage('RELOADING',700);setTimeout(()=>{ammo=12;reloading=false;updateHUD()},700)}
function hurt(n){hp-=n;document.querySelector('#damageFlash').style.opacity=.8;setTimeout(()=>document.querySelector('#damageFlash').style.opacity=0,100);updateHUD();if(hp<=0)endGame()}
function endGame(){gameOver=true;document.exitPointerLock?.();document.querySelector('#finalScore').textContent=score;document.querySelector('#finalWave').textContent=wave;document.querySelector('#gameOver').classList.remove('hidden')}
function reset(){for(const z of zombies)scene.remove(z);zombies.length=0;score=0;wave=1;hp=100;ammo=12;gameOver=false;gameStarted=true;updateHUD();document.querySelector('#gameOver').classList.add('hidden');spawnWave()}
function move(dt){const speed=(keys.ShiftLeft||keys.ShiftRight)?7:4;const dir=new THREE.Vector3();if(keys.KeyW)dir.z-=1;if(keys.KeyS)dir.z+=1;if(keys.KeyA)dir.x-=1;if(keys.KeyD)dir.x+=1;dir.normalize();const yaw=new THREE.Vector3();camera.getWorldDirection(yaw);yaw.y=0;yaw.normalize();const right=new THREE.Vector3().crossVectors(yaw,new THREE.Vector3(0,1,0)).normalize();camera.position.addScaledVector(yaw,dir.z*speed*dt);camera.position.addScaledVector(right,dir.x*speed*dt);camera.position.x=THREE.MathUtils.clamp(camera.position.x,-18,18);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-18,18)}
function updateZombies(dt){for(let i=zombies.length-1;i>=0;i--){const z=zombies[i];const v=new THREE.Vector3().subVectors(camera.position,z.position);v.y=0;const d=v.length();z.lookAt(camera.position.x,z.position.y,camera.position.z);if(d>1.55)z.position.addScaledVector(v.normalize(),z.userData.speed*dt);else{z.userData.attack-=dt;if(z.userData.attack<=0){hurt(8);z.userData.attack=.8}}z.position.y=0;if(z.position.distanceTo(camera.position)<1.2)z.position.addScaledVector(v.normalize(),-.2)}}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(gameStarted&&!gameOver){move(dt);updateZombies(dt);gun.rotation.z=Math.sin(performance.now()*.01)*.008}renderer.render(scene,camera)}

addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')reload();if(e.code==='Space'&&locked)camera.position.y=1.9});addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='Space')camera.position.y=1.7});renderer.domElement.addEventListener('mousedown',e=>{if(!gameStarted)return;if(!locked)renderer.domElement.requestPointerLock();else if(e.button===0)shoot()});addEventListener('mousemove',e=>{if(!locked||gameOver)return;camera.rotation.y-=e.movementX*.0022;camera.rotation.x-=e.movementY*.0022;camera.rotation.x=THREE.MathUtils.clamp(camera.rotation.x,-1.35,1.35)});document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===renderer.domElement;document.querySelector('#crosshair').style.opacity=locked?'1':'.5'});
document.querySelector('#startBtn').onclick=()=>{document.querySelector('#startScreen').classList.add('hidden');reset();renderer.domElement.requestPointerLock()};document.querySelector('#restartBtn').onclick=()=>{reset();renderer.domElement.requestPointerLock()};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});updateHUD();animate();
